services:
  app:
    build:
      args:
        user: farid
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    depends_on:
        - db
        - nginx
    image: blog
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - blog
  
  db:
    image: mysql:5.7
    container_name: blog-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - blog

  nginx:
    image: nginx:1.17-alpine
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - 81:81
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - blog

networks:
  blog:
    driver: bridge